# Generated by Django 4.2.6 on 2023-10-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('subestacao', models.CharField(max_length=120)),
                ('nivel_tensao_AT', models.CharField(max_length=120)),
                ('nivel_tensao_BT', models.CharField(max_length=120)),
            ],
        ),
    ]
